### ISSUE TITLE
Can't make, no libwebsockets in build dir

### ISSUE THREAD

**Issue by physiii** [lws-team/lws-esp32#1]
I am having trouble compiling. I can make the examples in lws-esp-idf but I get the following when trying to make from lws-esp32:

$ make
tail: cannot open '/home/user/lws-esp32/build/libwebsockets/libwebsockets-test-server.pem' for reading: No such file or directory
tail: cannot open '/home/user/code/lws-esp32/build/libwebsockets/libwebsockets-test-server.key.pem' for reading: No such file or directory
make[1]: genromfs: Command not found
/home/user/code/lws-esp32/main/component.mk:6: recipe for target 'prepare' failed
make[1]: *** [prepare] Error 127
/home/user/code/lws-esp-idf/make/project.mk:386: recipe for target 'main-build' failed
make: *** [main-build] Error 2

How do I get libwebsockets in my build directory?

**Comment by lws-team** [comment]
I have made a major update to the ESP32 stuff, you can now just use "pure" esp-idf without patches.

I'll push the new example projects shortly and post back here.

**Comment by lws-team** [comment]
Please grab first the factory project

https://github.com/warmcat/lws-esp32-factory

and then the test app

https://github.com/warmcat/lws-esp32-test-server-demos

**Comment by lws-team** [comment]
BTW you need to install your distro `genromfs`, in Ubuntu and Fedora it's in "genromfs" package.

**Comment by physiii** [comment]
Trying to follow your readme:

$ git clone https://github.com/warmcat/lws-esp32-factory
$ cd lws-esp32-factory
$ git submodules --init --recursive
^ this is a invalid command for git (2.7.4)

So I try:
$ git submodule update --init --recursive
Submodule 'components/libwebsockets' (https://github.com/warmcat/libwebsockets) registered for path 'components/libwebsockets'
Cloning into 'components/libwebsockets'...
remote: Counting objects: 14512, done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 14512 (delta 68), reused 0 (delta 0), pack-reused 14401
Receiving objects: 100% (14512/14512), 11.93 MiB | 11.77 MiB/s, done.
Resolving deltas: 100% (10997/10997), done.
Checking connectivity... done.
fatal: reference is not a tree: 53f8975e30e3a1fcf67958fc9b1f680b4389fe49
Unable to checkout '53f8975e30e3a1fcf67958fc9b1f680b4389fe49' in submodule path 'components/libwebsockets'

maybe...just maybe...

$ make
/home/physiii/code/lws-esp-idf/make/common.mk:10: /home/physiii/code/lws-esp32-factory/build/include/config/auto.conf: No such file or directory
Makefile:19: /home/physiii/code/lws-esp32-factory/components/libwebsockets/scripts/esp32.mk: No such file or directory
make: *** No rule to make target '/home/physiii/code/lws-esp32-factory/components/libwebsockets/scripts/esp32.mk'.  Stop.

...nope

**Comment by lws-team** [comment]
Yeah... if you don't check out lws, the whole app dependent on lws ain't gonna build.

This is because it's pointing to master of lws atm and github only keeps the current HEAD of that around.

I updated -factory to point to lws current master, but actually as a workaround you can just

```
cd components
git clone https://github.com/warmcat/libwebsockets
```

equally well.

**Comment by physiii** [comment]
Great now I can compile and upload but no access to http://192.168.4.1/factory.html even though I get an IP address. It fails to mount the ROMFS.

I (216) wifi: wifi firmware version: 9489f8a
I (216) wifi: config NVS flash: disabled
I (216) wifi: config nano formating: disabled
I (216) wifi: Init dynamic tx buffer num: 32
I (216) wifi: wifi driver task: 3ffc1d90, prio:23, stack:3584
I (226) wifi: Init static rx buffer num: 10
I (226) wifi: Init dynamic rx buffer num: 0
I (236) wifi: Init rx ampdu len mblock:7
I (236) wifi: Init lldesc rx ampdu entry mblock:4
I (246) wifi: wifi power manager task: 0x3ffc7138 prio: 21 stack: 2560
E (246) wifi: wifi_set_chan_range 1638 ret=1
I (256) wifi: wifi timer task: 3ffc81b8, prio:22, stack:3584
I (366) phy: phy_version: 350, Mar 22 2017, 15:02:06, 1, 0
I (366) wifi: mode : sta (24:0a:c4:04:b2:38) + softAP (24:0a:c4:04:b2:39)
4: No SSL certs... using port 80
4: Initial logging level 63
4: Libwebsockets version: 2.2.0 physiii@desktop-v2.0.0-344-g7faa716
4: IPV6 not compiled in
4:  Threads: 1 each 30 fds
4:  mem: platform fd map:   120 bytes
4:  Compiled with OpenSSL support
4:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
4:  mem: per-conn:          432 bytes + protocol rx buf
1: Failed to mount ROMFS at 0xc9b84 0xc9b84
4: setting mount default to factory
I (22876) wifi: n:6 0, o:6 0, ap:6 1, sta:0 0, prof:6
I (22876) wifi: station: 00:25:22:48:3f:ac join, AID=1, g, 20
W (22926) wifi: buffer null

I (57086) wifi: n:6 0, o:6 0, ap:6 1, sta:0 0, prof:6
I (57086) wifi: max connection already. unexpected aid!

I'd like to use a socket.io library like (https://github.com/washo4evr/Socket.io-v1.x-Library) because my server uses socket.io with the ESP8266 for all it's communication as well as other devices on the system.

**Comment by lws-team** [comment]
> I (57086) wifi: max connection already. unexpected aid!

This is what ESP32 does if more than the 1 allowed station tries to join the AP mode, or your PC or whatever you joined with still thinks it's joined to the previous AP session.  We just provide the esp-idf AP stuff restricted to 1 client and that's the behaviour you get.

Connect you pc wifi to something else and reconnect to the config AP.... otherwise one side or the other will eventually timeout the stale connection.

About socket.io, lws gives you a lowlevel control over ws + http for either or both client and server, ie those parts of the project you linked to; you have control over the REST parts of the URL in both cases as well.  So it should be possible to implement.

**Comment by physiii** [comment]
Can connect to http://192.168.4.1 but just the background image loads with no forms. 

I am getting this from the esp

> W (37386) wifi: buffer null

 and this in the browser

> Uncaught SyntaxError: Unexpected token e in JSON at position 239
>    at JSON.parse (<anonymous>)
 >   at WebSocket.got_packet ((index):158)

Is there something I need to change in protocol_esp32_lws_scan.c?

**Comment by lws-team** [comment]
Mmm...

 - `wifi: buffer null ` is coming out of the SDK... I looked up what it is, it's the wifi code trying to print a NULL buffer... it's unrelated to lws AFAIK since we don't mess with the SDK code.  It doesn't seem to make any problem in itself.

 - I erased all my flash and tried it, I don't get the error about 'e' in the JSON

 - As a security measure, since you can programmatically reboot into the factory setup (ie, an attacker may be able to do it) the factory.html page and some other features are only available if you rebooted into factory mode with GPIO14 grounded, indicating you're physically there with the device.

If GPIO14 isn't grounded, you will get this 

![esp32 sec1](https://libwebsockets.org/esp32-sec1.png)

I'll update the docs about it.

 - can you capture the bad JSON so I can see what is going on?  At this point tcpdump will do it, or add a div and set it to the msg.data and cut and paste

**Comment by lws-team** [comment]
I pushed an update on -factory that relaxes the requirement for the button if the SSL certs have not been uploaded... it will show the full factory UI then.

You'll need to pull this and then do `git submodule update --recursive`

**Comment by physiii** [comment]
Removed my build directory and tried to compile but I can't make after your last commit, undeclared variables in protocol_esp32_lws_scan.c:

> In file included from /home/physiii/code/lws-esp32-factory/main/./main.c:28:0:
/home/physiii/code/lws-esp32-factory/main/../components/libwebsockets/plugins/protocol_esp32_lws_scan.c: In function 'client_connection':
/home/physiii/code/lws-esp32-factory/main/../components/libwebsockets/plugins/protocol_esp32_lws_scan.c:181:35: error: 'CONFIG_LWS_OTA_SERVER_BASE_URL' undeclared (first use in this function)
  snprintf(path, sizeof(path) - 1, CONFIG_LWS_OTA_SERVER_BASE_URL "/" CONFIG_LWS_MODEL_NAME "/%s", file);
                                   ^
/home/physiii/code/lws-esp32-factory/main/../components/libwebsockets/plugins/protocol_esp32_lws_scan.c:181:35: note: each undeclared identifier is reported only once for each function it appears in
/home/physiii/code/lws-esp32-factory/main/../components/libwebsockets/plugins/protocol_esp32_lws_scan.c:181:66: error: expected ')' before string constant
  snprintf(path, sizeof(path) - 1, CONFIG_LWS_OTA_SERVER_BASE_URL "/" CONFIG_LWS_MODEL_NAME "/%s", file);
                                                                  ^
/home/physiii/code/lws-esp32-factory/main/../components/libwebsockets/plugins/protocol_esp32_lws_scan.c:187:14: error: 'CONFIG_LWS_OTA_SERVER_FQDN' undeclared (first use in this function)
  i.address = CONFIG_LWS_OTA_SERVER_FQDN;
              ^
/home/physiii/code/esp-idf/make/component_wrapper.mk:176: recipe for target 'main.o' failed
make[1]: *** [main.o] Error 1
/home/physiii/code/esp-idf/make/project.mk:386: recipe for target 'main-build' failed
make: *** [main-build] Error 2

Last working binary shows this on http://192.168.4.1

![image](https://cloud.githubusercontent.com/assets/6277642/24621272/8c49cc8c-1866-11e7-90d4-49497edfa9ae.png)

**Comment by lws-team** [comment]
OK... although I can't reproduce the problem with the CONFIG_LWS_OTA either on factory or the OTA app, I added checks around that code that they're defined.  It seems something different about your sdkconfig?  Might be interesting to diff your sdkconfig against the one shipped with the -factory project.

The missing text can just be due to the script being stopped by the JSON error you mentioned before.

If so, uncomment line 214 of `romfs-files/ap/factory.html`

```
// document.getElementById("main").textContent = msg.data + "\n";
```

and rebuild / flash.  This should dump the ws message to the div before trying to interpret it, so we can see it... cut and paste it here should shine some light.

**Comment by physiii** [comment]
You were right, my sdkconfig was changed - I can build now. I uncommented msg.data line and the esp is sending msg as null. Probably something with wifi: buffer null I'm getting from the esp.

I'm also getting this error:

>W (123056) wifi: buffer null

>W (123056) wifi: buffer null

>Guru Meditation Error of type LoadProhibited occurred on core  0. Exception was unhandled.
Register dump:
PC      : 0x400e08e6  PS      : 0x00060f30  A0      : 0x800e12ee  A1      : 0x3ffc86d0  
A2      : 0x00000034  A3      : 0x3ffd39ec  A4      : 0x40117fe8  A5      : 0x3ffd42ec  
A6      : 0x3ffd4938  A7      : 0x3ffb7c10  A8      : 0x800e08e4  A9      : 0x3ffc86b0  
A10     : 0x00000000  A11     : 0x000000d5  A12     : 0x3ffd39ec  A13     : 0x3ffd42ec  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000038  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  

>Backtrace: 0x400e08e6:0x3ffc86d0 0x400e12ee:0x3ffc87a0 0x40092e94:0x3ffc87c0 0x4009479e:0x3ffc8810

>Entering gdb stub now.
$T0b#e6

**Comment by lws-team** [comment]
No the `W (123056) wifi: buffer null` is symptomless here.

Can you update your esp-idf?  Just enter that dir and `git pull`, then go back and rebuild / retry -factory.

Current esp-idf attempts to give source backtraces.

**Comment by physiii** [comment]
I can use esp-idf examples without issues. But I no longer get a response from http://192.168.4.1

>~/code/esp-idf$ git pull
Already up-to-date.

>~/code/lws-esp32-factory$ git pull
Already up-to-date.

>~/code/lws-esp32-factory$ rm -rf build && make flash monitor
>I (216) wifi: wifi firmware version: 1f2a9e1
I (216) wifi: config NVS flash: disabled
I (216) wifi: config nano formating: disabled
I (216) wifi: Init dynamic tx buffer num: 32
I (226) wifi: Init static tx buffer num: 16
I (226) wifi: wifi driver task: 3ffc8948, prio:23, stack:3584
I (236) wifi: Init static rx buffer num: 10
I (236) wifi: Init dynamic rx buffer num: 0
I (236) wifi: Init rx ampdu len mblock:7
I (246) wifi: Init lldesc rx ampdu entry mblock:4
I (246) wifi: wifi power manager task: 0x3ffcdcf0 prio: 21 stack: 2560
E (256) wifi: wifi_set_chan_range 1658 ret=1
I (256) wifi: wifi timer task: 3ffced70, prio:22, stack:3584
I (286) phy: phy_version: 350, Mar 22 2017, 15:02:06, 1, 0
I (286) wifi: mode : sta (24:0a:c4:04:b2:38) + softAP (24:0a:c4:04:b2:39)
4: No SSL certs... using port 80
4: Initial logging level 63
4: Libwebsockets version: 2.2.0 physiii@desktop-v2.0.0-346-g34822f1
4: IPV6 not compiled in
4:  Threads: 1 each 30 fds
4:  mem: platform fd map:   120 bytes
4:  Compiled with OpenSSL support
4:  SSL disabled: no LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT
4:  mem: per-conn:          432 bytes + protocol rx buf
1: Failed to mount ROMFS at 0xca394 0xca394
4: setting mount default to factory
I (386) wifi: n:6 0, o:6 0, ap:6 1, sta:0 0, prof:6
I (386) wifi: station: 00:25:22:48:3f:ac join, AID=1, g, 20
W (906) wifi: buffer null

>$ ifconfig
wlan0 Link encap:Ethernet  HWaddr 00:25:22:48:3f:ac  
          inet addr:192.168.4.2  Bcast:192.168.4.255  Mask:255.255.255.0
          inet6 addr: fe80::e42f:6813:f594:3c57/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1 errors:0 dropped:0 overruns:0 frame:0
          TX packets:58 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:590 (590.0 B)  TX bytes:8829 (8.8 KB)

>$ curl 192.168.4.1
curl: (7) Failed to connect to 192.168.4.1 port 80: Connection refused

**Comment by lws-team** [comment]
Yeah... he could not find his ROMFS

```
1: Failed to mount ROMFS at 0xca394 0xca394
```
The

**Comment by lws-team** [comment]
... image consists of `[ normal image ] [ ROMFS ] [ manifest ]` all concatenated together.

When it runs, it walks the segments in the normal image and locates the ROMFS.

Did the 'flash' part flash ~920KB?

Any problems during the build?  Change of esp-idf should not affect this...

**Comment by physiii** [comment]
I flashed using this instead of make flash and I get to the blank factory setup page shown above. 

> $ python2 /home/physiii/code/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32 --port /dev/ttyUSB1 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x1000 /home/physiii/code/lws-esp32-factory/build/bootloader/bootloader.bin 0x10000 /home/physiii/code/lws-esp32-factory/build/lws-esp32-factory.bin 0x8000 /home/physiii/code/lws-esp32-factory/build/partitions.bin

Tried grounding GPIO 14, same result.

>E (32) boot: Force Button is Down 0x48eab
E (66) boot: force_factory 1 bs.ota_info.offset 53248

**Comment by lws-team** [comment]
Well, you can at lest run the code.  I use make flash here (from the -factory directory) with no problems.

GPIO14 detection seemed to work.

This is still sending a NULL JSON?  Not crashing any more?

**Comment by physiii** [comment]
Looks like invalid json but at least now I can see data and no crashing.

> SyntaxError: JSON.parse: unexpected non-digit at line 14 column 18 of the JSON data

console.log(msg.data)
>{ "model":"lws",
 "forced_button":"1",
 "serial":"04B239",
 "opts":"",
 "host":"lws-04B239",
 "region":"2",
 "ssl_pub":"0",
 "ssl_pri":"0",
 "mac":"240AC404B239",
 "ssid":"",
 "conn_ip":"",
 "conn_mask":"",
 "conn_gw":"",
 "img_factory": -e {
 "schema": "lws1",
 "model": "lws",
 "builder": "desktop-e ",
 "app": "lws-esp32-factory-e ",
 "user": "physiii-e ",
 "git": "25afc8a-dirty-e ",
 "date": "Wed Apr  5 09:20:09 CDT 2017-e ",
 "unixtime": "1491402009-e ",
 "file": "lws-esp32-factory-1491402009.bin-e ",
 "factory": "1-e "
},
 "img_ota":  { "date": "Empty" },
 "latest":  { },
 "inet":"0",
 "aps":[
...
]
}

**Comment by lws-team** [comment]
```
"img_factory": -e {
"schema": "lws1",
"model": "lws",
"builder": "desktop-e ",
"app": "lws-esp32-factory-e ",
"user": "physiii-e ",
"git": "25afc8a-dirty-e ",
"date": "Wed Apr 5 09:20:09 CDT 2017-e ",
"unixtime": "1491402009-e ",
"file": "lws-esp32-factory-1491402009.bin-e ",
"factory": "1-e "
},
```

This bit seems to have acquired `-e ` on most lines... the content here is generated at build time by make in `./build/json-buildinfo`... I can guess this is because you're on Ububtu or Debian where /bin/sh is not /bin/bash, I'm on Fedora where it is.  I pushed a patch forcing that bit of make to use bash... updating -factory and doing the `git submodule update --recursive` and re-make should be enough to fix it.

**Comment by physiii** [comment]
Awesome, we are up and running! I will post further issues in -factory.

**Comment by lws-team** [comment]
Heh... super.  FWIW it was running OK here from the start, but things like sh != bash are hard to find (since it works here...) without someone on a different distro tripping over them and working through it.

I will wait a bit and delete this repo, it's not needed in the "new way" with separate factory app and will just confuse people.  Lws README.md already points to the new repos.
