### ISSUE TITLE
lws-plat-esp32.c:582:11: error: 'CONFIG_LWS_MODEL_NAME' undeclared

### ISSUE THREAD

**Issue by a-super-admin** [lws-team/lws-esp32#2]
Hey, this config tool looks very promising but when I try ~/esp/**lws-esp32**# make all flash-romfs, I am getting this error. I copied libwebsockets to /root/esp/lws-esp-idf/components get rid of other dependency probs. sry for my noobines. 

---------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /root/esp/lws-esp32/build/libwebsockets
[  4%] Building C object CMakeFiles/websockets.dir/lib/lws-plat-esp32.c.o
/root/esp/lws-esp-idf/components/libwebsockets/lib/lws-plat-esp32.c:582:11: error: 'CONFIG_LWS_MODEL_NAME' undeclared here (not in a function)
  .model = CONFIG_LWS_MODEL_NAME,
           ^
CMakeFiles/websockets.dir/build.make:470: recipe for target 'CMakeFiles/websockets.dir/lib/lws-plat-esp32.c.o' failed
make[4]: *** [CMakeFiles/websockets.dir/lib/lws-plat-esp32.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/websockets.dir/all' failed
make[3]: *** [CMakeFiles/websockets.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make[2]: *** [all] Error 2
/root/esp/lws-esp-idf/components/libwebsockets/component.mk:19: recipe for target 'build' failed
make[1]: *** [build] Error 2
/root/esp/lws-esp-idf/make/project.mk:386: recipe for target 'libwebsockets-build' failed
make: *** [libwebsockets-build] Error 2

BTW,

when doing /esp/**lws-esp32-factory**# make flash monitor its flashing the esp32, getting into AP mode having 192.168.4.2 but http://192.168.4.1/(factory.html) is not reachble.
What is the difference for those 2 projects any way?

 

THX

**Comment by lws-team** [comment]
This project got replaced by

https://github.com/warmcat/lws-esp32-factory

which has many improvements, please restart there.  Notice you don't need to change esp-idf any more, the romfs is attached to the image, there are separate factory and user ota support, so please read the README.md carefully.
